development:
  adapter: postgresql
  encoding: unicode
  database: koolio_development
  pool: 5
  username: admin
  password: admin123

test:
  adapter: postgresql
  encoding: unicode
  database: koolio_test
  pool: 5
  username: admin
  password: admin123